[
  "XMODIFIERS, @im=ibus"
  "GTK_IM_MODULE, ibus"
  "QT_IM_MODULE, ibus"
  "QT_QPA_PLATFORMTHEME, qt5ct"
  "WLR_NO_HARDWARE_CURSORS, 1"
  "XCURSOR_SIZE, 24"
  "LIBVA_DRIVER_NAME,nvidia"
  "XDG_SESSION_TYPE,wayland"
  "GBM_BACKEND,nvidia-drm"
  "__GLX_VENDOR_LIBRARY_NAME,nvidia"
]
