# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [ "module_blacklist=i915" "resume_offset=34494464" "nvidia.NVreg_PreserveVideoMemoryAllocations=1" ];
  boot.resumeDevice = "/dev/disk/by-uuid/437dcadd-77a2-4cdb-be32-345b821a52cf";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/437dcadd-77a2-4cdb-be32-345b821a52cf";
    fsType = "ext4";
  };
  boot.initrd.luks.devices."luks-1c7b9d2f-467a-4299-bfb7-2136ccd6082f".device = "/dev/disk/by-uuid/1c7b9d2f-467a-4299-bfb7-2136ccd6082f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/365F-1409";
    fsType = "vfat";
  };

  boot.initrd.luks.devices."luks-0618d838-6e33-4612-8635-c896d8cdca85".device = "/dev/disk/by-uuid/0618d838-6e33-4612-8635-c896d8cdca85";
  fileSystems."/home/okrag/disk" = {
    fsType = "ext4";
    device = "/dev/mapper/luks-0618d838-6e33-4612-8635-c896d8cdca85";
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = 8 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
